### ISSUE TITLE
[Bug]燃料がない

### ISSUE THREAD

**Issue by kazu0617** [smk7758/ComputerCraft_computer_source#1]
https://github.com/kazu0617/ComputerCraft_computer_source/blob/master/fish.lua#L91
 ここに入るとき、燃料がすでになくなってて釣りできない、と言ったパターンが有り。
なので恐らくこの釣りする前の段階でfuelが2を返すときに釣りをやめさせ、チェストにアイテム移動する、と言った作業が必要かと。

**Comment by smk7758** [comment]
対策を講じました。
